name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Add server to known_hosts
        run: ssh-keyscan -H 37.27.35.83 >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Add server to known_hosts
        run: |
         mkdir -p ~/.ssh
         ssh-keyscan -H 37.27.35.83 >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /home/gearpro01efr/htdocs/gearpro01e.com
          remote_host: 37.27.35.83
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
